[package]
name = "sleef-shim-rs"
version = "0.1.0"
authors = ["zachmatson <zacharywdmatson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cmake = "0.1"
